spring:
  datasource:
    url: jdbc:mysql:///openapi
    password: 1234
    username: root
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq: 
    host: rabbitmq.qfjava.cn
    post: 8800 
